# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MathML-Entities-Approximate
version:      0.20
version_from: lib/MathML/Entities/Approximate.pm
installdirs:  site
requires:
    MathML::Entities:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
